// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Internal Links field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.internalLinks[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    internalLinks: prismicT.GroupField<Simplify<FooterDocumentDataInternalLinksItem>>;
    /**
     * Social Links field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.social_links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_links: prismicT.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;
    /**
     * Copyright field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Copyright content
     * - **API ID Path**: footer.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright: prismicT.RichTextField;
}
/**
 * Item in Footer → Internal Links
 *
 */
export interface FooterDocumentDataInternalLinksItem {
    /**
     * Link Label field in *Footer → Internal Links*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Link label
     * - **API ID Path**: footer.internalLinks[].link_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link_label: prismicT.RichTextField;
    /**
     * Link field in *Footer → Internal Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link
     * - **API ID Path**: footer.internalLinks[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in Footer → Social Links
 *
 */
export interface FooterDocumentDataSocialLinksItem {
    /**
     * Social Link field in *Footer → Social Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link URL
     * - **API ID Path**: footer.social_links[].social_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link: prismicT.LinkField;
    /**
     * Social Icon Image field in *Footer → Social Links*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.social_links[].social_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    social_icon: prismicT.ImageField<never>;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
    /**
     * Meta Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: My title for Search Engine
     * - **API ID Path**: homepage.meta_title
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta Description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The description that will appear in search engine
     * - **API ID Path**: homepage.meta_description
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * CanonicalLink field in *Homepage*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.canonicalLink
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    canonicalLink: prismicT.LinkField;
    /**
     * Social Cards - Facebook & Twitter field in *Homepage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.social_cards[]
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_cards: prismicT.GroupField<Simplify<HomepageDocumentDataSocialCardsItem>>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = AccordionSlice | HeroBannerSlice | SocialFeedFlickrSlice;
/**
 * Item in Homepage → Social Cards - Facebook & Twitter
 *
 */
export interface HomepageDocumentDataSocialCardsItem {
    /**
     * Social Card Image field in *Homepage → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.social_cards[].social_card_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    social_card_image: prismicT.ImageField<never>;
    /**
     * Social Card Title field in *Homepage → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.social_cards[].social_card_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_title: prismicT.KeyTextField;
    /**
     * Social card description field in *Homepage → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.social_cards[].social_card_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_description: prismicT.KeyTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Landing page documents */
interface LandingPageDocumentData {
    /**
     * Slice Zone field in *Landing page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LandingPageDocumentDataSlicesSlice>;
    /**
     * Meta Title field in *Landing page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: My title for Search Engine
     * - **API ID Path**: landing_page.meta_title
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta Description field in *Landing page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The description that will appear in search engine
     * - **API ID Path**: landing_page.meta_description
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * CanonicalLink field in *Landing page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.canonicalLink
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    canonicalLink: prismicT.LinkField;
    /**
     * Social Cards - Facebook & Twitter field in *Landing page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.social_cards[]
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_cards: prismicT.GroupField<Simplify<LandingPageDocumentDataSocialCardsItem>>;
}
/**
 * Slice for *Landing page → Slice Zone*
 *
 */
type LandingPageDocumentDataSlicesSlice = HeroBannerSlice | AccordionSlice | SocialFeedFlickrSlice | FeaturesSlice;
/**
 * Item in Landing page → Social Cards - Facebook & Twitter
 *
 */
export interface LandingPageDocumentDataSocialCardsItem {
    /**
     * Social Card Image field in *Landing page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.social_cards[].social_card_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    social_card_image: prismicT.ImageField<never>;
    /**
     * Social Card Title field in *Landing page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.social_cards[].social_card_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_title: prismicT.KeyTextField;
    /**
     * Social card description field in *Landing page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.social_cards[].social_card_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_description: prismicT.KeyTextField;
}
/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<LandingPageDocumentData>, "landing_page", Lang>;
/** Content for Menu documents */
interface MenuDocumentData {
    /**
     * Logo field in *Menu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Company name field in *Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Company name
     * - **API ID Path**: menu.company_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    company_name: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Menu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MenuDocumentDataSlicesSlice>;
}
/**
 * Slice for *Menu → Slice Zone*
 *
 */
type MenuDocumentDataSlicesSlice = MenuSlice;
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
export type AllDocumentTypes = FooterDocument | HomepageDocument | LandingPageDocument | MenuDocument;
/**
 * Primary content in Accordion → Primary
 *
 */
interface AccordionSliceDefaultPrimary {
    /**
     * Title field in *Accordion → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Section title
     * - **API ID Path**: accordion.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Accordion → Items
 *
 */
export interface AccordionSliceDefaultItem {
    /**
     * Title field in *Accordion → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: First level label
     * - **API ID Path**: accordion.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Content field in *Accordion → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Content
     * - **API ID Path**: accordion.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Accordion`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AccordionSliceDefaultPrimary>, Simplify<AccordionSliceDefaultItem>>;
/**
 * Slice variation for *Accordion*
 *
 */
type AccordionSliceVariation = AccordionSliceDefault;
/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: `Accordion`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AccordionSlice = prismicT.SharedSlice<"accordion", AccordionSliceVariation>;
/**
 * Primary content in Features → Primary
 *
 */
interface FeaturesSliceDefaultPrimary {
    /**
     * Title field in *Features → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Section title
     * - **API ID Path**: features.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Features → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Section description
     * - **API ID Path**: features.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceDefaultItem {
    /**
     * Feature Title field in *Features → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Item title
     * - **API ID Path**: features.items[].feature_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    feature_title: prismicT.RichTextField;
    /**
     * Feature Description field in *Features → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Item description
     * - **API ID Path**: features.items[].feature_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    feature_description: prismicT.RichTextField;
    /**
     * Feature Icon Image field in *Features → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features.items[].feature_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    feature_icon: prismicT.ImageField<never>;
}
/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FeaturesSliceDefaultPrimary>, Simplify<FeaturesSliceDefaultItem>>;
/**
 * Primary content in Features → Primary
 *
 */
interface FeaturesSliceWithImagePrimary {
    /**
     * Title field in *Features → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Section title
     * - **API ID Path**: features.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Features → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Section description
     * - **API ID Path**: features.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Section Title field in *Features → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: features.primary.section_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    section_title: prismicT.TitleField;
    /**
     * Section description field in *Features → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features.primary.section_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    section_description: prismicT.RichTextField;
    /**
     * Section Image field in *Features → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features.primary.section_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    section_image: prismicT.ImageField<never>;
    /**
     * Image position field in *Features → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: features.primary.image_position
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    image_position: prismicT.BooleanField;
}
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceWithImageItem {
    /**
     * Feature Title field in *Features → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Item title
     * - **API ID Path**: features.items[].feature_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    feature_title: prismicT.RichTextField;
    /**
     * Feature Description field in *Features → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Item description
     * - **API ID Path**: features.items[].feature_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    feature_description: prismicT.RichTextField;
    /**
     * Feature Icon Image field in *Features → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features.items[].feature_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    feature_icon: prismicT.ImageField<never>;
}
/**
 * With image variation for Features Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceWithImage = prismicT.SharedSliceVariation<"withImage", Simplify<FeaturesSliceWithImagePrimary>, Simplify<FeaturesSliceWithImageItem>>;
/**
 * Slice variation for *Features*
 *
 */
type FeaturesSliceVariation = FeaturesSliceDefault | FeaturesSliceWithImage;
/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSlice = prismicT.SharedSlice<"features", FeaturesSliceVariation>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceDefaultPrimary {
    /**
     * Title Top line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Top line content
     * - **API ID Path**: hero_banner.primary.title_top_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top_line: prismicT.TitleField;
    /**
     * Title Bottom Line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Bottom line content
     * - **API ID Path**: hero_banner.primary.title_bottom_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom_line: prismicT.TitleField;
    /**
     * Description field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Section description
     * - **API ID Path**: hero_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *HeroBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in HeroBanner → Items
 *
 */
export interface HeroBannerSliceDefaultItem {
    /**
     * Cta Label field in *HeroBanner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Link label
     * - **API ID Path**: hero_banner.items[].cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
    /**
     * Cta Link field in *HeroBanner → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link URL
     * - **API ID Path**: hero_banner.items[].cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Cta Type field in *HeroBanner → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select button type
     * - **Default Value**: Primary
     * - **API ID Path**: hero_banner.items[].cta_type
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    cta_type: prismicT.SelectField<"Primary" | "Secondary", "filled">;
}
/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroBannerSliceDefaultPrimary>, Simplify<HeroBannerSliceDefaultItem>>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceWithoutCtaPrimary {
    /**
     * Title Top line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Top line content
     * - **API ID Path**: hero_banner.primary.title_top_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top_line: prismicT.TitleField;
    /**
     * Title Bottom Line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Bottom line content
     * - **API ID Path**: hero_banner.primary.title_bottom_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom_line: prismicT.TitleField;
    /**
     * Description field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Section description
     * - **API ID Path**: hero_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *HeroBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Without Cta variation for HeroBanner Slice
 *
 * - **API ID**: `withoutCta`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceWithoutCta = prismicT.SharedSliceVariation<"withoutCta", Simplify<HeroBannerSliceWithoutCtaPrimary>, never>;
/**
 * Primary content in HeroBanner → Primary
 *
 */
interface HeroBannerSliceWithSignUpAndMediaPrimary {
    /**
     * Form top message field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Short message
     * - **API ID Path**: hero_banner.primary.form_top_message
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    form_top_message: prismicT.RichTextField;
    /**
     * Title Top line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Top line content
     * - **API ID Path**: hero_banner.primary.title_top_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top_line: prismicT.TitleField;
    /**
     * Title Bottom Line field in *HeroBanner → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Bottom line content
     * - **API ID Path**: hero_banner.primary.title_bottom_line
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom_line: prismicT.TitleField;
    /**
     * Description field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Section description
     * - **API ID Path**: hero_banner.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Form Label field in *HeroBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Form label, not displayed
     * - **API ID Path**: hero_banner.primary.form_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    form_label: prismicT.KeyTextField;
    /**
     * Form placeholder field in *HeroBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Email field placeholder
     * - **API ID Path**: hero_banner.primary.form_placeholder
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    form_placeholder: prismicT.KeyTextField;
    /**
     * Form Cta Label field in *HeroBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Link label
     * - **API ID Path**: hero_banner.primary.form_cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    form_cta_label: prismicT.KeyTextField;
    /**
     * Media Thumbnail field in *HeroBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_banner.primary.media_thumbnail
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    media_thumbnail: prismicT.ImageField<never>;
    /**
     * Show play video button field in *HeroBanner → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: hero_banner.primary.show_play_video_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    show_play_video_button: prismicT.BooleanField;
    /**
     * Privacy message field in *HeroBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Privacy message
     * - **API ID Path**: hero_banner.primary.privacy_message
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    privacy_message: prismicT.RichTextField;
}
/**
 * With sign up and media variation for HeroBanner Slice
 *
 * - **API ID**: `withSignUpAndMedia`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSliceWithSignUpAndMedia = prismicT.SharedSliceVariation<"withSignUpAndMedia", Simplify<HeroBannerSliceWithSignUpAndMediaPrimary>, never>;
/**
 * Slice variation for *HeroBanner*
 *
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault | HeroBannerSliceWithoutCta | HeroBannerSliceWithSignUpAndMedia;
/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: `HeroBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroBannerSlice = prismicT.SharedSlice<"hero_banner", HeroBannerSliceVariation>;
/**
 * Primary content in MenuItem → Primary
 *
 */
interface MenuSliceDefaultPrimary {
    /**
     * Label field in *MenuItem → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Label
     * - **API ID Path**: menu.primary.label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    label: prismicT.RichTextField;
    /**
     * Link field in *MenuItem → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link
     * - **API ID Path**: menu.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MenuSliceDefaultPrimary>, never>;
/**
 * Primary content in MenuItem → Primary
 *
 */
interface MenuSliceDropdownPrimary {
    /**
     * Dropdown label field in *MenuItem → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: First level label
     * - **API ID Path**: menu.primary.label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    label: prismicT.RichTextField;
}
/**
 * Item in MenuItem → Items
 *
 */
export interface MenuSliceDropdownItem {
    /**
     * Second level link field in *MenuItem → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Second level link
     * - **API ID Path**: menu.items[].second_level_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    second_level_link: prismicT.LinkField;
    /**
     * Second level label field in *MenuItem → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Second level label
     * - **API ID Path**: menu.items[].second_level_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    second_level_label: prismicT.RichTextField;
    /**
     * Second level description field in *MenuItem → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Second level description paragraph
     * - **API ID Path**: menu.items[].second_level_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    second_level_description: prismicT.RichTextField;
}
/**
 * Dropdown variation for MenuItem Slice
 *
 * - **API ID**: `dropdown`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDropdown = prismicT.SharedSliceVariation<"dropdown", Simplify<MenuSliceDropdownPrimary>, Simplify<MenuSliceDropdownItem>>;
/**
 * Slice variation for *MenuItem*
 *
 */
type MenuSliceVariation = MenuSliceDefault | MenuSliceDropdown;
/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSlice = prismicT.SharedSlice<"menu", MenuSliceVariation>;
/**
 * Primary content in SocialFeedFlickr → Primary
 *
 */
interface SocialFeedFlickrSliceDefaultPrimary {
    /**
     * Title field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Title
     * - **API ID Path**: social_feed_flickr.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Social Link Label field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Link label
     * - **API ID Path**: social_feed_flickr.primary.social_link_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_link_label: prismicT.KeyTextField;
    /**
     * Social Link Url field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link URL
     * - **API ID Path**: social_feed_flickr.primary.social_link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link_url: prismicT.LinkField;
    /**
     * Number Of Posts field in *SocialFeedFlickr → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Number Of Posts to display
     * - **API ID Path**: social_feed_flickr.primary.number_of_posts
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    number_of_posts: prismicT.NumberField;
}
/**
 * Default variation for SocialFeedFlickr Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SocialFeedFlickr`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialFeedFlickrSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SocialFeedFlickrSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SocialFeedFlickr*
 *
 */
type SocialFeedFlickrSliceVariation = SocialFeedFlickrSliceDefault;
/**
 * SocialFeedFlickr Shared Slice
 *
 * - **API ID**: `social_feed_flickr`
 * - **Description**: `SocialFeedFlickr`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialFeedFlickrSlice = prismicT.SharedSlice<"social_feed_flickr", SocialFeedFlickrSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FooterDocumentData, FooterDocumentDataInternalLinksItem, FooterDocumentDataSocialLinksItem, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocumentDataSocialCardsItem, HomepageDocument, LandingPageDocumentData, LandingPageDocumentDataSlicesSlice, LandingPageDocumentDataSocialCardsItem, LandingPageDocument, MenuDocumentData, MenuDocumentDataSlicesSlice, MenuDocument, AllDocumentTypes, AccordionSliceDefaultPrimary, AccordionSliceDefaultItem, AccordionSliceDefault, AccordionSliceVariation, AccordionSlice, FeaturesSliceDefaultPrimary, FeaturesSliceDefaultItem, FeaturesSliceDefault, FeaturesSliceWithImagePrimary, FeaturesSliceWithImageItem, FeaturesSliceWithImage, FeaturesSliceVariation, FeaturesSlice, HeroBannerSliceDefaultPrimary, HeroBannerSliceDefaultItem, HeroBannerSliceDefault, HeroBannerSliceWithoutCtaPrimary, HeroBannerSliceWithoutCta, HeroBannerSliceWithSignUpAndMediaPrimary, HeroBannerSliceWithSignUpAndMedia, HeroBannerSliceVariation, HeroBannerSlice, MenuSliceDefaultPrimary, MenuSliceDefault, MenuSliceDropdownPrimary, MenuSliceDropdownItem, MenuSliceDropdown, MenuSliceVariation, MenuSlice, SocialFeedFlickrSliceDefaultPrimary, SocialFeedFlickrSliceDefault, SocialFeedFlickrSliceVariation, SocialFeedFlickrSlice };
    }
}
