// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import ContentSectionImage from './ContentSectionImage';
import Features from './Features';
import HeroBanner from './HeroBanner';
import MenuItem from './MenuItem';
import SocialFeedFlickr from './SocialFeedFlickr';

export {
	Accordion,
	ContentSectionImage,
	Features,
	HeroBanner,
	MenuItem,
	SocialFeedFlickr,
};

export const components = {
	accordion: Accordion,
	content_section_image: ContentSectionImage,
	features: Features,
	hero_banner: HeroBanner,
	menu: MenuItem,
	social_feed_flickr: SocialFeedFlickr,
};
